// common
export const SET_DATA = "SET_DATA";
export const SET_DATA_CANCLE = "SET_DATA_CANCLE";
export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";
export const SHOW_LOADING_PART = "SHOW_LOADING_PART";
export const HIDE_LOADING_PART = "HIDE_LOADING_PART";
export const SHOW_POPUP = "SHOW_POPUP";
export const ALERT_POPUP = "ALERT_POPUP";
export const CONFIRM_POPUP = "CONFIRM_POPUP";
export const HIDE_POPUP = "HIDE_POPUP";

//검색 필터
export const SET_FILTER_INQUERY = "SET_FILTER_INQUERY";
export const SET_FILTER_OPTION = "SET_FILTER_OPTION";

//검색 리스트 API
export const GET_SEARCH_LIST = "GET_SEARCH_LIST";
export const GET_SEARCH_LIST_SUCCESS = "GET_SEARCH_LIST_SUCCESS";
export const GET_SEARCH_LIST_FAIL = "GET_SEARCH_LIST_FAIL";
export const SET_SEARCH_KEYWORD = "SET_SEARCH_KEYWORD";
export const SET_SEARCH_KEYWORD_CLEAR = "SET_SEARCH_KEYWORD_CLEAR";
export const SET_SEARCH_STATUS = "SET_SEARCH_STATUS";
export const SET_SEARCH_ALL_SUCCESS = "SET_SEARCH_ALL_SUCCESS";

//상품리뷰 dashboard
export const GET_DASHBOARD_LIST = "GET_DASHBOARD_LIST";
export const GET_DASHBOARD_LIST_SUCCESS = "GET_DASHBOARD_LIST_SUCCESS";
export const GET_DASHBOARD_LIST_FAIL = "GET_DASHBOARD_LIST_FAIL";

//상품리뷰 overview
export const GET_PRDRVOVIEW = "GET_PRDRVOVIEW";
export const GET_PRDRVOVIEW_SUCCESS = "GET_PRDRVOVIEW_SUCCESS";
export const GET_PRDRVOVIEW_FAIL = "GET_PRDRVOVIEW_FAIL";
export const GET_PRDRVOVIEW_LAYER = "GET_PRDRVOVIEW_LAYER";
export const GET_PRDRVOVIEW_LAYER_SUCCESS = "GET_PRDRVOVIEW_LAYER_SUCCESS";
export const GET_PRDRVOVIEW_LAYER_FAIL = "GET_PRDRVOVIEW_LAYER_FAIL";
export const GET_PRDRVOVIEW_FILTER_GUBUN = "GET_PRDRVOVIEW_FILTER_GUBUN";

//상품리뷰 overview detail
export const GET_PRDRVOVIEW_DETAIL = "GET_PRDRVOVIEW_DETAIL";
export const GET_PRDRVOVIEW_DETAIL_SUCCESS = "GET_PRDRVOVIEW_DETAIL_SUCCESS";
export const GET_PRDRVOVIEW_DETAIL_FAIL = "GET_PRDRVOVIEW_DETAIL_FAIL";

//상품리뷰 overview summary
export const GET_PRDRVOVIEW_SUMMARY = "GET_PRDRVOVIEW_SUMMARY";
export const GET_PRDRVOVIEW_SUMMARY_SUCCESS = "GET_PRDRVOVIEW_SUMMARY_SUCCESS";
export const GET_PRDRVOVIEW_SUMMARY_FAIL = "GET_PRDRVOVIEW_SUMMARY_FAIL";

//History Actions
export const SET_EXCEL_HISTORY = "SET_EXCEL_HISTORY";
export const SET_EXCEL_HISTORY_SUCCESS = "SET_EXCEL_HISTORY_SUCCESS";
export const SET_EXCEL_HISTORY_FAIL = "SET_EXCEL_HISTORY_FAIL";

//알람 관리
export const GET_ALARM_LIST = "GET_ALARM_LIST";
export const GET_ALARM_LIST_SUCCESS = "GET_ALARM_LIST_SUCCESS";
export const GET_ALARM_LIST_FAIL = "GET_ALARM_LIST_FAIL";
export const SET_ALARM_INSERT = "SET_ALARM_INSERT";
export const SET_ALARM_INSERT_SUCCESS = "SET_ALARM_INSERT_SUCCESS";
export const SET_ALARM_INSERT_FAIL = "SET_ALARM_INSERT_FAIL";
export const SET_ALARM_DELETE = "SET_ALARM_DELETE";
export const SET_ALARM_DELETE_SUCCESS = "SET_ALARM_DELETE_SUCCESS";
export const SET_ALARM_DELETE_FAIL = "SET_ALARM_DELETE_FAIL";
export const SET_ALARM_UPDATE = "SET_ALARM_UPDATE";
export const SET_ALARM_UPDATE_SUCCESS = "SET_ALARM_UPDATE_SUCCESS";
export const SET_ALARM_UPDATE_FAIL = "SET_ALARM_UPDATE_FAIL";
export const SET_ALARM_ONOFF = "SET_ALARM_ONOFF";
export const SET_ALARM_ONOFF_SUCCESS = "SET_ALARM_ONOFF_SUCCESS";
export const SET_ALARM_ONOFF_FAIL = "SET_ALARM_ONOFF_FAIL";
export const GET_ALARM_SEND_LIST = "GET_ALARM_SEND_LIST";
export const GET_ALARM_SEND_LIST_SUCCESS = "GET_ALARM_SEND_LIST_SUCCESS";
export const GET_ALARM_SEND_LIST_FAIL = "GET_ALARM_SEND_LIST_FAIL";