name: $(Date:yyyyMMdd)$(Rev:-r)

trigger:
  branches:
    include:
      - devs
  paths:
    include:
      - /
    exclude:
      - /pipeline

resources:
  repositories:
    - repository: etrend-app-helm
      type: git
      name: etrend/etrend-app-helm
      ref: refs/heads/main

stages:
  - stage: stage1
    pool:
      vmImage: ubuntu-latest
    jobs:
      - job: job1
        displayName: 'AWS ECR Image Push'
        variables:
          - template: ./dev/variables.yaml
        steps:
          - template: ./dev/stage1_job1_steps.yaml
  - stage: stage2
    pool:
      vmImage: ubuntu-latest
    jobs:
      - job: job1
        displayName: 'Update Image Tag'
        variables:
          - template: ./dev/variables.yaml
        steps:
          - template: ./dev/stage2_job1_steps_by_helm.yaml
