export default function handler(req, res) {
  const data = {
    ROWDATA: [
      {
        rv_gubun: "cd1001",
        rv_prdt: "[피코크] 삼원가든 꽃갈비찜 700g",
        rv_grade: 4.1,
        rv_count: 300,
        rv_posit: 62,
        rv_negat: 23,
        rv_negat_ratio: 52,
        rv_negat_inc: 12,
      },
      {
        rv_gubun: "cd1002",
        rv_prdt: "[피코크] 삼원가든 꽃갈비찜 700g",
        rv_grade: 4.2,
        rv_count: 100,
        rv_posit: 32,
        rv_negat: 68,
        rv_negat_ratio: 68,
        rv_negat_inc: 68,
      },
      {
        rv_gubun: "cd1001",
        rv_prdt: "[피코크] 삼원가든 꽃갈비찜 700g",
        rv_grade: 4.1,
        rv_count: 300,
        rv_posit: 62,
        rv_negat: 23,
        rv_negat_ratio: 52,
        rv_negat_inc: 12,
      },
      {
        rv_gubun: "cd1001",
        rv_prdt: "[피코크] 삼원가든 꽃갈비찜 700g",
        rv_grade: 4.2,
        rv_count: 100,
        rv_posit: 32,
        rv_negat: 68,
        rv_negat_ratio: 68,
        rv_negat_inc: 68,
      },
      {
        rv_gubun: "cd1002",
        rv_prdt: "[피코크] 삼원가든 꽃갈비찜 700g",
        rv_grade: 4.1,
        rv_count: 300,
        rv_posit: 62,
        rv_negat: 23,
        rv_negat_ratio: 52,
        rv_negat_inc: 12,
      },
      {
        rv_gubun: "cd1001",
        rv_prdt: "[피코크] 삼원가든 꽃갈비찜 700g",
        rv_grade: 4.2,
        rv_count: 100,
        rv_posit: 32,
        rv_negat: 68,
        rv_negat_ratio: 68,
        rv_negat_inc: 68,
      },
      {
        rv_gubun: "cd1002",
        rv_prdt: "[피코크] 삼원가든 꽃갈비찜 700g",
        rv_grade: 4.1,
        rv_count: 300,
        rv_posit: 62,
        rv_negat: 23,
        rv_negat_ratio: 52,
        rv_negat_inc: 12,
      },
      {
        rv_gubun: "cd1002",
        rv_prdt: "[피코크] 삼원가든 꽃갈비찜 700g",
        rv_grade: 4.2,
        rv_count: 100,
        rv_posit: 32,
        rv_negat: 68,
        rv_negat_ratio: 68,
        rv_negat_inc: 68,
      },
      {
        rv_gubun: "cd1001",
        rv_prdt: "[피코크] 삼원가든 꽃갈비찜 700g",
        rv_grade: 4.1,
        rv_count: 300,
        rv_posit: 62,
        rv_negat: 23,
        rv_negat_ratio: 52,
        rv_negat_inc: 12,
      },
      {
        rv_gubun: "cd1002",
        rv_prdt: "[피코크] 삼원가든 꽃갈비찜 700g",
        rv_grade: 4.2,
        rv_count: 100,
        rv_posit: 32,
        rv_negat: 68,
        rv_negat_ratio: 68,
        rv_negat_inc: 68,
      },
      {
        rv_gubun: "cd1001",
        rv_prdt: "[피코크] 삼원가든 꽃갈비찜 700g",
        rv_grade: 4.1,
        rv_count: 300,
        rv_posit: 62,
        rv_negat: 23,
        rv_negat_ratio: 52,
        rv_negat_inc: 12,
      },
      {
        rv_gubun: "cd1002",
        rv_prdt: "[피코크] 삼원가든 꽃갈비찜 700g",
        rv_grade: 4.2,
        rv_count: 100,
        rv_posit: 32,
        rv_negat: 68,
        rv_negat_ratio: 68,
        rv_negat_inc: 68,
      },
      {
        rv_gubun: "cd1002",
        rv_prdt: "[피코크] 삼원가든 꽃갈비찜 700g",
        rv_grade: 4.2,
        rv_count: 100,
        rv_posit: 32,
        rv_negat: 68,
        rv_negat_ratio: 68,
        rv_negat_inc: 68,
      },
      {
        rv_gubun: "cd1002",
        rv_prdt: "[피코크] 삼원가든 꽃갈비찜 700g",
        rv_grade: 4.2,
        rv_count: 100,
        rv_posit: 32,
        rv_negat: 68,
        rv_negat_ratio: 68,
        rv_negat_inc: 68,
      },
    ],
  };
  res.json(data);
}
